In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
df = pd.read_csv('/Users/seanleong/Desktop/Projects/Predicting_H1N1_Flu/Data/Flu_Shot_Learning_Predict_H1N1_and_Seasonal_Flu_Vaccines_-_Training_Features.csv')
labels = pd.read_csv('/Users/seanleong/Desktop/Projects/Predicting_H1N1_Flu/Data/Flu_Shot_Learning_Predict_H1N1_and_Seasonal_Flu_Vaccines_-_Training_Labels.csv')

In [3]:
df.shape

(26707, 36)

In [4]:
labels.columns

Index(['respondent_id', 'h1n1_vaccine', 'seasonal_vaccine'], dtype='object')

In [5]:
df.columns

Index(['respondent_id', 'h1n1_concern', 'h1n1_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_h1n1', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_h1n1_vacc_effective', 'opinion_h1n1_risk',
       'opinion_h1n1_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'hhs_geo_region', 'census_msa',
       'household_adults', 'household_children', 'employment_industry',
       'employment_occupation'],
      dtype='object')

In [6]:
df.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [7]:
labels.head()

   respondent_id  h1n1_vaccine  seasonal_vaccine
0              0             0                 0
1              1             0                 1
2              2             0                 0
3              3             0                 1
4              4             0                 0

In [8]:
def missing_zero_values_table(df):
    ''' 
    Returns a dataframe showing the number of missing or zero values in the 
    input dataframe

    Parameters
    ----------
    df: pandas dataframe 

    Returns:
    --------
    mz_table: pandas dataframe
    '''
    zero_val = (df == 0.00).astype(int).sum(axis=0)
    mis_val = df.isnull().sum()
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    mz_table = pd.concat([zero_val, mis_val, mis_val_percent], axis=1)
    mz_table = mz_table.rename(
    columns = {0 : 'Zero Values', 1 : 'Missing Values', 2 : '% of Total Values'})
    mz_table['Total Zero Missing Values'] = mz_table['Zero Values'] + mz_table['Missing Values']
    mz_table['% Total Zero Missing Values'] = 100 * mz_table['Total Zero Missing Values'] / len(df)
    mz_table['Data Type'] = df.dtypes
    mz_table = mz_table[
        mz_table.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(1)
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns and " + str(df.shape[0]) + " Rows.\n"      
        "There are " + str(mz_table.shape[0]) +
            " columns that have missing values.")
#         mz_table.to_excel('D:/sampledata/missing_and_zero_values.xlsx', freeze_panes=(1,0), index = False)
    return mz_table

In [9]:
new_df = pd.merge(df, labels, on='respondent_id', how='inner')

In [10]:
new_df.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,h1n1_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0

In [11]:
missing_zero_values_table(new_df)

Your selected dataframe has 38 columns and 26707 Rows.
There are 30 columns that have missing values.

,Zero Values,Missing Values,% of Total Values,Total Zero Missing Values,% Total Zero Missing Values,Data Type
employment_occupation,0,13470,50.4,13470,50.4,object
employment_industry,0,13330,49.9,13330,49.9,object
health_insurance,1736,12274,46.0,14010,52.5,float64
income_poverty,0,4423,16.6,4423,16.6,object
doctor_recc_h1n1,19139,2160,8.1,21299,79.8,float64
doctor_recc_seasonal,16453,2160,8.1,18613,69.7,float64
rent_or_own,0,2042,7.6,2042,7.6,object
employment_status,0,1463,5.5,1463,5.5,object
marital_status,0,1408,5.3,1408,5.3,object
education,0,1407,5.3,1407,5.3,object
chronic_med_condition,18446,971,3.6,19417,72.7,float64
child_under_6_months,23749,820,3.1,24569,92.0,float64
health_worker,23004,804,3.0,23808,89.1,float64
opinion_seas_sick_from_vacc,0,537,2.0,537,2.0,float64
opinion_seas_risk,0,514,1.9,514,1.9,float64
opinion_seas_vacc_effective,0,462,1.7,462,1.7,float64
opinion_h1n1_sick_from_vacc,0,395,1.5,395,1.5,float64
opinion_h1n1_vacc_effective,0,391,1.5,391,1.5,float64
opinion_h1n1_risk,0,388,1.5,388,1.5,float64
household_adults,8056,249,0.9,8305,31.1,float64
household_children,18672,249,0.9,18921,70.8,float64
behavioral_avoidance,7271,208,0.8,7479,28.0,float64
behavioral_touch_face,8578,128,0.5,8706,32.6,float64
h1n1_knowledge,2506,116,0.4,2622,9.8,float64
h1n1_concern,3296,92,0.3,3388,12.7,float64
behavioral_large_gatherings,17073,87,0.3,17160,64.3,float64
behavioral_outside_home,17644,82,0.3,17726,66.4,float64
behavioral_antiviral_meds,25335,71,0.3,25406,95.1,float64
behavioral_wash_hands,4650,42,0.2,4692,17.6,float64
behavioral_face_mask,24847,19,0.1,24866,93.1,float64

In [12]:
no_health_insurance = new_df[new_df['health_insurance'].isnull()]

In [13]:
no_health_insurance['employment_status'].value_counts()

Employed              5962
Not in Labor Force    4370
Unemployed             592
Name: employment_status, dtype: int64

In [14]:
health_insurance = new_df[new_df['health_insurance'].notnull()]

In [15]:
health_insurance['employment_status'].value_counts()

Employed              7598
Not in Labor Force    5861
Unemployed             861
Name: employment_status, dtype: int64

In [16]:
def fillpoverty(row):
    if row['age_group'] == "65+ Years" and row['employment_status'] == "Not in Labor Force":
        return "Retired"
    elif row['employment_status'] == "Unemployed" or row['employment_status']  == "Not in Labor Force":
        return "Unemployed"
    else:
        return "N/A"

In [17]:
new_df["income_poverty"] = new_df.apply(lambda x: fillpoverty(x) if pd.isnull(x['income_poverty']) else x['income_poverty'], axis = 1)

In [18]:
new_df = new_df[new_df['employment_status'].notna()]

In [19]:
new_df.drop(columns=['health_insurance', 'doctor_recc_h1n1', 'doctor_recc_seasonal'], inplace=True)

In [46]:
def fill_with_mean(df, column):
    df[column].fillna(np.mean(df[column]), inplace=True)

In [50]:
opinion_columns = ['opinion_h1n1_vacc_effective', 'opinion_seas_vacc_effective',
                    'opinion_seas_risk', 'opinion_h1n1_sick_from_vacc',
                    'opinion_seas_sick_from_vacc', 'opinion_h1n1_risk']

for opinion in opinion_columns:
    fill_with_mean(new_df, opinion)

In [51]:
missing_zero_values_table(new_df)

Your selected dataframe has 35 columns and 25244 Rows.
There are 19 columns that have missing values.

,Zero Values,Missing Values,% of Total Values,Total Zero Missing Values,% Total Zero Missing Values,Data Type
employment_occupation,0,12007,47.6,12007,47.6,object
employment_industry,0,11867,47.0,11867,47.0,object
rent_or_own,0,686,2.7,686,2.7,object
chronic_med_condition,17881,220,0.9,18101,71.7,float64
behavioral_avoidance,6777,189,0.7,6966,27.6,float64
education,0,157,0.6,157,0.6,object
marital_status,0,141,0.6,141,0.6,object
behavioral_touch_face,8092,114,0.5,8206,32.5,float64
h1n1_knowledge,2179,107,0.4,2286,9.1,float64
behavioral_large_gatherings,16173,78,0.3,16251,64.4,float64
behavioral_outside_home,16750,75,0.3,16825,66.6,float64
h1n1_concern,3056,75,0.3,3131,12.4,float64
behavioral_antiviral_meds,23986,65,0.3,24051,95.3,float64
behavioral_wash_hands,4371,34,0.1,4405,17.4,float64
behavioral_face_mask,23526,17,0.1,23543,93.3,float64
health_worker,22392,14,0.1,22406,88.8,float64
household_adults,7685,11,0.0,7696,30.5,float64
household_children,18052,11,0.0,18063,71.6,float64
child_under_6_months,23181,4,0.0,23185,91.8,float64

Dummy employment occupation and employment industry

Drop columns: health_insurance, doctor_recc_h1n1, doctor_rec_seasonal

Remove NAs for: household_adults, household_children, employment_status

Replace with Unknown: education, marital_status

Fill opinions with median